#!/usr/bin/env python3
"""Re-geocode and patch exported site JS files without the full plotting stack."""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from src.geocode import (
    attach_coordinates,
    canonical_affiliation_key,
    geocode_affiliations,
    _load_json,
    _lookup_override,
)
from src.programme import load_talks

AUSTRALIA_CENTROID = (-24.7761086, 134.755)
NEW_ZEALAND_CENTROID = (-41.500083, 172.834408)
COUNTRY_CENTROIDS = {AUSTRALIA_CENTROID, NEW_ZEALAND_CENTROID}
LOCATIONS_PATH = PROJECT_ROOT / "js" / "locations.js"
EMISSIONS_PATH = PROJECT_ROOT / "js" / "emissions-data.js"
OVERRIDES_PATH = PROJECT_ROOT / "data" / "geocode_overrides.json"


def _read_js_export(path: Path, export_name: str) -> dict:
    source = path.read_text(encoding="utf-8")
    prefix = f"export const {export_name} = "
    start = source.index(prefix) + len(prefix)
    end = source.rindex(";\n")
    return json.loads(source[start:end])


def _write_js_export(path: Path, export_name: str, payload: dict, generator: str) -> None:
    body = (
        f"/** Generated by {generator} – do not edit by hand. */\n"
        f"export const {export_name} = {json.dumps(payload, ensure_ascii=True, indent=2)};\n"
    )
    path.write_text(body, encoding="utf-8")


def _coords_for_key(key: str, overrides: dict) -> tuple[float, float] | None:
    override = _lookup_override(key, overrides)
    if override and override.get("latitude") is not None:
        return float(override["latitude"]), float(override["longitude"])
    return None


def _patch_location(location: dict, overrides: dict) -> bool:
    affiliation = location.get("affiliation") or ""
    key = canonical_affiliation_key(affiliation)
    coords = _coords_for_key(key, overrides)
    if coords is None:
        lat = location.get("lat")
        lon = location.get("lon")
        if lat is None or lon is None:
            return False
        rounded = (round(float(lat), 6), round(float(lon), 6))
        if rounded not in COUNTRY_CENTROIDS:
            return False
        return False
    lat, lon = coords
    changed = location.get("lat") != lat or location.get("lon") != lon
    location["lat"] = lat
    location["lon"] = lon
    location["geocode_level"] = "institute"
    return changed


def _patch_object_tree(node, overrides: dict) -> int:
    changed = 0
    if isinstance(node, dict):
        affiliation = node.get("affiliation")
        if affiliation and "lat" in node and "lon" in node:
            if _patch_location(node, overrides):
                changed += 1
        for value in node.values():
            changed += _patch_object_tree(value, overrides)
    elif isinstance(node, list):
        for item in node:
            changed += _patch_object_tree(item, overrides)
    return changed


def patch_locations_file(path: Path, overrides: dict) -> int:
    payload = _read_js_export(path, "SITE_DATA")
    changed = _patch_object_tree(payload, overrides)
    if changed:
        _write_js_export(path, "SITE_DATA", payload, "fix_site_coordinates.py")
    return changed


def patch_emissions_file(path: Path, overrides: dict) -> int:
    payload = _read_js_export(path, "EMISSIONS_DATA")
    changed = 0
    for pool_name in ("speakers", "all_delegates"):
        pool = payload.get(pool_name)
        if not pool:
            continue
        for location in pool.get("locations", []):
            if _patch_location(location, overrides):
                changed += 1
    if changed:
        _write_js_export(path, "EMISSIONS_DATA", payload, "fix_site_coordinates.py")
    return changed


def refresh_talk_geocodes() -> None:
    talks = load_talks()
    affiliations = talks["affiliation"].dropna().unique()
    geocoded = geocode_affiliations(affiliations, show_progress=True)
    talks_geo = attach_coordinates(talks, geocoded)
    by_key: dict[str, tuple[float, float]] = {}
    for _, row in talks_geo.dropna(subset=["latitude", "longitude"]).iterrows():
        key = canonical_affiliation_key(str(row["affiliation"]))
        by_key[key] = (float(row["latitude"]), float(row["longitude"]))
    return by_key


def main() -> None:
    overrides = _load_json(OVERRIDES_PATH)
    loc_changed = patch_locations_file(LOCATIONS_PATH, overrides)
    em_changed = patch_emissions_file(EMISSIONS_PATH, overrides)
    print(f"Patched {loc_changed} locations in {LOCATIONS_PATH.name}")
    print(f"Patched {em_changed} locations in {EMISSIONS_PATH.name}")


if __name__ == "__main__":
    main()
