/** Add talk_titles and talk_titles_by_author to js/locations.js from programme data. */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const locationsPath = join(root, "js/locations.js");
const programmePath = join(root, "data/programme.json");

const locationsSource = readFileSync(locationsPath, "utf8");
const payloadMatch = locationsSource.match(/export const SITE_DATA = (\{[\s\S]*\});\s*$/);
if (!payloadMatch) {
  throw new Error(`Could not parse SITE_DATA from ${locationsPath}`);
}
const payload = JSON.parse(payloadMatch[1]);
const programme = JSON.parse(readFileSync(programmePath, "utf8"));

function talkAuthors(talk) {
  const authors = Array.isArray(talk.authors)
    ? talk.authors.map((author) => String(author || "").trim()).filter(Boolean)
    : [];
  if (authors.length) return authors;
  const presenter = String(talk.presenter || "").trim();
  return presenter ? [presenter] : [];
}

function buildTalkTitlesByAuthor() {
  const index = new Map();

  for (const session of programme.sessions || []) {
    for (const talk of session.talks || []) {
      const title = talk.title?.trim();
      if (!title) continue;

      const presenter = String(talk.presenter || talk.authors?.[0] || "").trim();
      const authors = talkAuthors(talk);
      if (!authors.length) continue;

      for (const author of authors) {
        const bucket = index.get(author) || new Map();
        const primary = author === presenter || (!presenter && author === authors[0]);
        const existing = bucket.get(title);
        if (!existing || (primary && !existing.primary)) {
          bucket.set(title, { title, primary });
        }
        index.set(author, bucket);
      }
    }
  }

  const result = {};
  for (const [author, titles] of [...index.entries()].sort(([a], [b]) => a.localeCompare(b))) {
    result[author] = [...titles.values()].sort((a, b) => {
      if (a.primary !== b.primary) return a.primary ? -1 : 1;
      return a.title.localeCompare(b.title);
    });
  }
  return result;
}

const talkTitlesByAuthor = buildTalkTitlesByAuthor();
payload.talk_titles_by_author = talkTitlesByAuthor;

let updatedSpeakers = 0;
for (const location of payload.locations || []) {
  for (const speaker of location.speaker_details || []) {
    const talkTitles = talkTitlesByAuthor[speaker.name] || [];
    speaker.talk_titles = talkTitles;
    if (talkTitles.length) updatedSpeakers += 1;
  }
}

const jsBody =
  "/** Generated by export_attendee_site_data – do not edit by hand. */\n" +
  `export const SITE_DATA = ${JSON.stringify(payload, null, 2)};\n`;
writeFileSync(locationsPath, jsBody, "utf8");
console.log(`Wrote ${locationsPath}`);
console.log(`Authors with talk titles: ${Object.keys(talkTitlesByAuthor).length.toLocaleString()}`);
console.log(`Speakers with talk titles: ${updatedSpeakers.toLocaleString()}`);
