"""Export talk metadata for the static site (no plotting dependencies)."""

from __future__ import annotations

import json
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import pandas as pd


def _talk_authors(row: pd.Series, *, presenter_col: str = "presenter") -> list[str]:
    authors = row.get("authors")
    if isinstance(authors, list) and authors:
        return [str(author).strip() for author in authors if str(author).strip()]
    presenter = row.get(presenter_col)
    if pd.isna(presenter) or not str(presenter).strip():
        return []
    return [str(presenter).strip()]


def build_talk_catalog(
    df: pd.DataFrame,
    *,
    title_col: str = "title",
    abstract_col: str = "abstract",
    presenter_col: str = "presenter",
) -> dict[str, Any]:
    by_id: dict[str, dict[str, Any]] = {}
    title_index: dict[str, list[str]] = {}

    for _, row in df.iterrows():
        talk_id = row.get("talk_id")
        title = row.get(title_col)
        if pd.isna(talk_id) or pd.isna(title) or not str(title).strip():
            continue
        talk_id_text = str(talk_id).strip()
        title_text = str(title).strip()
        abstract = row.get(abstract_col)
        presenter = row.get(presenter_col)
        authors = _talk_authors(row, presenter_col=presenter_col)
        talk = {
            "id": talk_id_text,
            "title": title_text,
            "authors": authors,
            "presenter": "" if pd.isna(presenter) else str(presenter).strip(),
            "abstract": "" if pd.isna(abstract) else str(abstract).strip(),
            "session_title": ""
            if pd.isna(row.get("session_title"))
            else str(row["session_title"]).strip(),
            "date": "" if pd.isna(row.get("date")) else str(row["date"]).strip(),
            "start": "" if pd.isna(row.get("start")) else str(row["start"]).strip(),
        }
        by_id[talk_id_text] = talk
        title_index.setdefault(title_text.casefold(), []).append(talk_id_text)

    return {"by_id": by_id, "title_index": title_index}


def export_talks_catalog(
    df: pd.DataFrame,
    *,
    save_path: str | Path = "js/talks.js",
) -> Path:
    """Export full talk metadata for the static site talk detail panel."""
    catalog = build_talk_catalog(df)
    payload = {
        "meta": {
            "generated_at": datetime.now(UTC).isoformat(timespec="seconds"),
            "talk_count": len(catalog["by_id"]),
        },
        "by_id": catalog["by_id"],
        "title_index": catalog["title_index"],
    }
    output_path = Path(save_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        "/** Generated by export_talks_catalog – do not edit by hand. */\n"
        f"export const TALKS_DATA = {json.dumps(payload, ensure_ascii=True, indent=2)};\n",
        encoding="utf-8",
    )
    return output_path
